// ===== Data layer =====
//
// Lists come from static JSON generated by scripts/build-data.mjs and served
// straight from the CDN, so browsing the app costs zero API calls. Only a
// Pokemon's flavor text still hits the network, via the REST API, which is
// CDN-cached and has no rate limit.
//
// The GraphQL endpoint is deliberately not used: it is rate limited to
// 100 calls/h per IP and returns 429 without CORS headers when exhausted,
// which surfaces in the browser as an unexplained network failure.

const REST_URL = 'https://pokeapi.co/api/v2';
const DATA_URL = new URL('../data/', import.meta.url);

// Finite set of failure modes the UI knows how to explain.
export const ErrorKind = {
  NETWORK: 'network',
  RATE_LIMIT: 'ratelimit',
  NOT_FOUND: 'notfound',
  UNKNOWN: 'unknown',
};

export class ApiError extends Error {
  constructor(kind, message) {
    super(message);
    this.name = 'ApiError';
    this.kind = kind;
  }
}

async function getJson(url) {
  let res;
  try {
    res = await fetch(url);
  } catch (err) {
    throw new ApiError(ErrorKind.NETWORK, err.message);
  }
  if (res.status === 404) throw new ApiError(ErrorKind.NOT_FOUND, `Not found: ${url}`);
  if (res.status === 429) throw new ApiError(ErrorKind.RATE_LIMIT, 'Rate limited');
  if (!res.ok) throw new ApiError(ErrorKind.UNKNOWN, `HTTP ${res.status}`);
  try {
    return await res.json();
  } catch {
    // A catch-all redirect serving index.html would land here as a 200.
    throw new ApiError(ErrorKind.UNKNOWN, `Invalid JSON from ${url}`);
  }
}

// One request per dataset per session. The CDN and the browser cache handle
// repeat visits, so there is nothing to persist ourselves.
const datasets = new Map();

function loadDataset(name) {
  if (!datasets.has(name)) {
    const pending = getJson(new URL(`${name}.json`, DATA_URL)).catch((err) => {
      datasets.delete(name); // so the retry button can actually retry
      throw err;
    });
    datasets.set(name, pending);
  }
  return datasets.get(name);
}

// ===== LISTS =====
export const fetchPokemonList = () => loadDataset('pokemon');
export const fetchMoves = () => loadDataset('moves');
export const fetchAbilities = () => loadDataset('abilities');
export const fetchItems = () => loadDataset('items');
export const fetchEvolutions = () => loadDataset('evolutions');
export const fetchLearnsets = () => loadDataset('learnsets');

// ===== POKEMON DETAIL =====
const idFromUrl = url => Number(url.replace(/\/$/, '').split('/').pop());

// Optional: the page renders fine without it, so a failure here is not fatal.
async function fetchDescription(id) {
  try {
    const species = await getJson(`${REST_URL}/pokemon-species/${id}`);
    const newest = species.flavor_text_entries
      .filter(e => e.language.name === 'es')
      .sort((a, b) => idFromUrl(b.version.url) - idFromUrl(a.version.url))[0];
    return newest?.flavor_text.replace(/[\n\f\r]/g, ' ').trim() || '';
  } catch {
    return '';
  }
}

export async function fetchPokemonDetail(id) {
  const [pokemon, abilities] = await Promise.all([
    loadDataset('pokemon'),
    loadDataset('abilities'),
  ]);

  const p = pokemon.find(x => x.id === id);
  if (!p) return null;

  const abilityInfo = new Map(abilities.map(a => [a.name, a]));
  const speciesName = other => pokemon.find(x => x.id === other)?.nameEs || null;

  return {
    id: p.id,
    name: p.name,
    nameEs: p.nameEs,
    nameEn: p.nameEn,
    types: p.types,
    height: p.height,
    weight: p.weight,
    stats: p.stats,
    evYield: p.evYield || {},
    abilities: p.abilities.map(a => {
      const info = abilityInfo.get(a.nameEn);
      return {
        name: info?.nameEs || a.nameEn,
        nameEs: info?.nameEs || a.nameEn,
        nameEn: a.nameEn,
        displayEn: info?.nameEn || a.nameEn,
        isHidden: a.isHidden,
        descriptionEs: info?.descriptionEs || '',
        descriptionEn: info?.descriptionEn || '',
        effect: info?.effect || '',
      };
    }),
    captureRate: p.captureRate,
    isLegendary: p.isLegendary,
    isMythical: p.isMythical,
    description: await fetchDescription(id),
    prevName: id > 1 ? speciesName(id - 1) : null,
    nextName: speciesName(id + 1),
  };
}

// ===== POKEMON SEARCH (for calculator) =====
export async function searchPokemon(term) {
  const pokemon = await loadDataset('pokemon');
  const q = term.toLowerCase();

  return pokemon
    .filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.nameEs.toLowerCase().includes(q) ||
      p.nameEn.toLowerCase().includes(q)
    )
    .slice(0, 10)
    .map(p => ({
      id: p.id,
      name: p.name,
      nameEs: p.nameEs,
      nameEn: p.nameEn,
      stats: p.stats,
    }));
}

// Drop caches written by the old GraphQL client; they are dead weight and
// filling the quota made every write fail silently.
export function purgeLegacyCache() {
  try {
    for (const key of Object.keys(localStorage)) {
      if (key.startsWith('pkutils_') && key !== 'pkutils_theme' && key !== 'pkutils_lang') {
        localStorage.removeItem(key);
      }
    }
  } catch {}
}
